apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: ubuntu:16.04
        name: test
        command: ["tail", "-f", "/dev/null"]
        securityContext:
          runAsUser: 1000
          fsGroup: 1000 #only applicable for clusters that run Kubernetes version 1.13 or later
        volumeMounts:
        - name: <volume_name>
          mountPath: /cos-test
      volumes:
      - name: <volume_name>
        persistentVolumeClaim:
          claimName: s3fs-pvc-create-bucket

