apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-test-1
  namespace: <project_name>
  labels:
    app: os-test-1
spec:
  selector:
    matchLabels:
      app: os-test-1
  replicas: 1
  template:
    metadata:
      labels:
        app: os-test-1
    spec:
      containers:
      - image: ubuntu:16.04
        name: test
        command: ["tail", "-f", "/dev/null"]
        # securityContext:
        #   runAsUser: 1000
        #   fsGroup: 1000 #only applicable for clusters that run Kubernetes version 1.13 or later
        volumeMounts:
        - name: cos-mount-1
          mountPath: /cos-test-1
      volumes:
      - name: cos-mount-1
        persistentVolumeClaim:
          claimName: s3fs-pvc-create-bucket

